stages:
  - build
  - test
  - sast

build:
  stage: build
  image: maven:3.9-eclipse-temurin-21
  script:
    - mvn clean package -DskipTests

test:
  stage: test
  image: maven:3.9-eclipse-temurin-21
  script:
    - mvn test

sast:
  stage: sast
  image: redshop/opengrep:1.30.0
  script:
    - opengrep scan --config auto --error .