stages:
  - build
  - test
  - sast
  - sca
  - secrets
  - package
# - trivy
  - deploy

build:
  stage: build
  image: maven:3.9-eclipse-temurin-21
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  image: maven:3.9-eclipse-temurin-21
  script:
    - mvn test

sast:
  stage: sast
  image: redshop/opengrep:1.30.0
  script:
    - opengrep scan --config auto --error .

sca-sbom:
  stage: sca
  image: redshop/syft:1.51.1
  script:
    - syft dir:. -o syft-json=sbom.json
  artifacts:
    paths:
      - sbom.json

sca-scan:
  stage: sca
  image: redshop/grype:0.118.0
  needs:
    - job: sca-sbom
      artifacts: true
  script:
    - grype sbom:sbom.json

gitleaks:
  stage: secrets
  image: redshop/gitleaks:8.30.1
  script:
    - gitleaks git .

package:
  stage: package
  image: docker:27-cli
  needs:
    - job: build
      artifacts: true
  script:
    - docker build -t redshop/redshop:$CI_COMMIT_SHORT_SHA .

#trivy:
#  stage: trivy
#  image: redshop/trivy:0.74.0
#  script:
#    - trivy image --exit-code 1 --severity HIGH,CRITICAL redshop/redshop:$CI_COMMIT_SHORT_SHA

deploy:
  stage: deploy
  image: docker:27-cli
  needs:
    - job: package
  script:
    - id
    - ls -ln /var/run/docker.sock
    - docker version