env:
  contexts:
    - name: RedShop

      urls:
        - "http://192.168.59.135/"

      includePaths:
        - "http://192\\.168\\.59\\.135/.*"

      excludePaths:
        - "http://192\\.168\\.59\\.135/logout.*"

      authentication:
        method: browser

        parameters:
          loginPageUrl: "http://192.168.59.135/login"
          browserId: firefox-headless
          loginPageWait: 3
          stepDelay: 0
          diagnostics: true

        verification:
          method: poll
          loggedInRegex: "My Account|Account|Profile|Dashboard|Diagnostics"
          loggedOutRegex: "Welcome back|Sign in|Login"
          pollFrequency: 1
          pollUnits: requests
          pollUrl: "http://192.168.59.135/account"
          pollPostData: ""

      sessionManagement:
        method: autodetect

      users:
        - name: dast-user
          credentials:
            username: peyman
            password: peyman


parameters:
  failOnError: true
  failOnWarning: false
  continueOnFailure: true
  progressToStdout: true


jobs:

  # ==========================================================
  # Traditional Spider
  # ==========================================================

  - type: spider
    parameters:
      context: RedShop
      user: dast-user
      url: "http://192.168.59.135/"

      maxDuration: 5
      maxDepth: 10
      maxChildren: 100

      acceptCookies: true
      handleParameters: use_all

      logoutAvoidance: true

      parseComments: true
      parseGit: false

      postForm: false
      processForm: false

      sendRefererHeader: true


  # ==========================================================
  # Client Spider
  # ==========================================================

  - type: spiderClient
    parameters:
      context: RedShop
      user: dast-user
      url: "http://192.168.59.135/"

      maxDuration: 5
      maxCrawlDepth: 5
      maxChildren: 100


  # ==========================================================
  # Passive Scan
  # ==========================================================

  - type: passiveScan-wait
    parameters:
      maxDuration: 5


  # ==========================================
  # Active Scan - Path Traversal ONLY
  # ==========================================

  - type: activeScan
    parameters:
      context: RedShop
      user: dast-user

      url: "http://192.168.59.135/account/avatar/view"

      maxRuleDurationInMins: 2
      maxScanDurationInMins: 2

      policy: Path-Traversal-Only

      handleAntiCSRFTokens: true


    policyDefinition:
      defaultStrength: Low
      defaultThreshold: "Off"

      rules:
        - id: 6
          name: "Path Traversal"
          strength: Low
          threshold: Low


  # ==========================================================
  # Passive Scan
  # ==========================================================

  - type: passiveScan-wait
    parameters:
      maxDuration: 5


  # ==========================================================
  # HTML Report
  # ==========================================================

  - type: report
    parameters:
      template: modern
      reportDir: /zap/wrk/redshop-dast/
      reportFile: zap-report.html
      reportTitle: "RedShop DAST Security Report"